### ISSUE TITLE
LiveTile support for Windows 10 seems to not work

### ISSUE THREAD

**Issue by hl2guide** [Gabboxl/FluentWeather#11]
For me LiveTile support does not seem to work. Just shows an icon.

![1](https://github.com/Gabboxl/FluentWeather/assets/17044982/7ff2e6eb-b017-4c91-8f0a-873da57bc9ab)

-Release: 1.2.0
-OS: Windows 10 Pro

**Comment by Gabboxl** [comment]
Hi, did you enable it in the app's settings?

**Comment by hl2guide** [comment]
> Hi, did you enable it in the app's settings?

ah, I expected it to be on by default.

**Comment by Gabboxl** [comment]
You're right, will probably enable it by default on Windows 10, to not waste resources on Windows 11 as they are not available there.
