### ISSUE TITLE
Reduce background opacity

### ISSUE THREAD

**Issue by zxbmmmmmmmmm** [Gabboxl/FluentWeather#12]
Sometimes, text may become unclear due to its proximity to the background color(Especially in light theme)
![image](https://github.com/Gabboxl/FluentWeather/assets/96322503/25d45ec5-c2be-44b8-9578-119351a6e04d)

Reducing the opacity of the background may be better
like this:
![image](https://github.com/Gabboxl/FluentWeather/assets/96322503/89e7da74-7eca-4bc5-aec3-80bd35695a4c)

Alternatively, the theme can be set to dark mode by default
![image](https://github.com/Gabboxl/FluentWeather/assets/96322503/13280b95-b9c9-494f-b719-f09ccc013d4b)

**Comment by Gabboxl** [comment]
Hmm that's weird, the theme should be set to dark always already. Will see what's wrong, thank you!

May I know what's the name of that other weather app you are using please? :)

**Comment by zxbmmmmmmmmm** [comment]
> May I know what's the name of that other weather app you are using please? :)

It's my another project with the same name

https://github.com/zxbmmmmmmmmm/FluentWeather

**Comment by Gabboxl** [comment]
> > May I know what's the name of that other weather app you are using please? :)
> 
> It's my another project with the same name
> 
> [zxbmmmmmmmmm/FluentWeather](https://github.com/zxbmmmmmmmmm/FluentWeather)

Oh interesting, this means competition :))

**Comment by Gabboxl** [comment]
Fixed with https://github.com/Gabboxl/FluentWeather/commit/b0c09bfad5901e0d11c4e543537f451324e8b06a thanks!

**Comment by zxbmmmmmmmmm** [comment]
> Oh interesting, this means competition :))

I started this project around July and I didn't know you had already used this name at the time 
However, if time permits, Im willing to contribute to your project :)

**Comment by Gabboxl** [comment]
> > Oh interesting, this means competition :))
> 
> I started this project around July and I didn't know you had already used this name at the time However, if time permits, Im willing to contribute to your project :)

Oh alright, that's a weird coincidence haha. 
You're very welcome to contribute, thanks a lot if you do so!
