### ISSUE TITLE
Text color issue in Light mode

### ISSUE THREAD

**Issue by CalicoApricot** [Gabboxl/FluentWeather#18]
When using system-wide light mode the text color in the app is always black and harder to read, unlike when using dark mode which have white text.

![Screenshot 2023-09-15 214118](https://github.com/Gabboxl/FluentWeather/assets/15978297/bdd19df2-447f-48ed-93c0-2b8ebc62eac3)
_FluentWeather when using Windows 11 in Light mode_

**Comment by Gabboxl** [comment]
Hi, this issue has already been reported and fixed. A new version will be published soon :)
