### ISSUE TITLE
Sluggish scrolling in main page cause of acrylic

### ISSUE THREAD

**Issue by itsWindows11** [Gabboxl/FluentWeather#2]

**Comment by Gabboxl** [comment]
Hmm this depends mostly on the graphics power of the device, maybe I could add an option to disable the acrylic effects.

**Comment by itsWindows11** [comment]
This is more problematic on battery saver mode in laptops, I guess.

**Comment by Gabboxl** [comment]
I tested the behavior on a laptop and the acrylic gets disabled as soon the laptop enters in battery saver mode, so Windows already handles this case. The acrylic gets disabled when transparency effects are disabled in Windows settings, also.

I will add an option to disable them in the app still, in case someone has problems with them.
