### ISSUE TITLE
LiveTile Improvements - Timestamp and Freshness Check

### ISSUE THREAD

**Issue by hl2guide** [Gabboxl/FluentWeather#20]
Please consider improving the LiveTile feature in these ways:
- A text-based label for last checked (e.g. 3m ago)
- Only update LiveTile if the data has changed since last check (avoids rotate animation with no new data)

![example tile](https://github.com/Gabboxl/FluentWeather/assets/17044982/892a77a7-bbf0-46a0-afbb-a5c121b2e7a3)

**Comment by Gabboxl** [comment]
Yeah, I would have done that but designing livetiles is not a simple job :((. Will look into this again btw.

**Comment by Gabboxl** [comment]
> Just hoping would it be possible to move all texts in the live tile a bit lower,  currently texts on wide live tiles are all stuck on the top, leaving an entire blank space below, which could look much better if all the texts are moved to a lower spot.
> ![image](https://github.com/Gabboxl/FluentWeather/assets/62368342/45e2effe-7923-4e64-923d-820355bf57bd)
> 

This is weird, mine looks like the one in the first post of this issue. Are you using more than 125% of scaling?

**Comment by PIndividual** [comment]
Yes, I'm with 150%

**Comment by PIndividual** [comment]
Well, most modern laptops with screens using high resolutions has high scaling value

**Comment by Gabboxl** [comment]
> Yes, I'm with 150%

> Well, most modern laptops with screens using high resolutions has high scaling value

Yeah, well Live Tiles are an old piece of technology that is very difficult to design. I will not spend time optimizing the tiles for high DPI displays, it requires too much time and testing, unfortunately

**Comment by Gabboxl** [comment]
Hi, just an update about this issue. After some tests, I came to the conclusion that adding a label with the time of the last update is not possible because there isn't enough space on the tile.
Unfortunately the scaling of the live tiles on Windows is not really coherent, and I don't think I can really do something about it.

If someone wants to contribute or has a solution to this, please reopen this issue!
