### ISSUE TITLE
Links in settings view are hard to read

### ISSUE THREAD

**Issue by niels9001** [Gabboxl/FluentWeather#21]
![image](https://github.com/Gabboxl/FluentWeather/assets/9866362/c6888ebb-a0e7-429b-9d71-443e8ef9aec1)

**Comment by maisondasilva** [comment]
@niels9001 It looks like another version, does the error still occur?

https://github.com/Gabboxl/FluentWeather/releases/tag/1.2.2

**Comment by Gabboxl** [comment]
This issue doesn't seem to be present in release 1.2.2, please reopen the issue if you continue to experience it.
