### ISSUE TITLE
Polishing on the Hours interface

### ISSUE THREAD

**Issue by maisondasilva** [Gabboxl/FluentWeather#23]
I see this line and also the bar together, is there a possibility that the line is cut and just below the % and the scroll bar is lower?

![image](https://github.com/Gabboxl/FluentWeather/assets/11423362/91eca296-16a3-4e99-9612-040efc9ec642)

**Comment by Gabboxl** [comment]
This has been fixed in the 1.2.2 release, could you check, please?

**Comment by maisondasilva** [comment]
Yes, waiting for an update via the Microsoft Store to let you know @Gabboxl

**Comment by maisondasilva** [comment]
The new update is much better, I would like to know if I can translate the name of the application into my language and you can also display this name in the Microsoft Store in my language, this would help users find the application more easily @Gabboxl

**Comment by Gabboxl** [comment]
> The new update is much better, I would like to know if I can translate the name of the application into my language and you can also display this name in the Microsoft Store in my language, this would help users find the application more easily @Gabboxl

The app's name is untranslatable. the listings of the Store are updatable only by myself manually, unfortunately :(

**Comment by maisondasilva** [comment]
@Gabboxl  I just saw an app whose name appears differently in the Microsoft Store for each language

Tema Dinâmico
https://www.microsoft.com/pt-br/store/p/dynamic-theme/9nblggh1zbkw

Dynamic Theme
https://www.microsoft.com/en-us/store/p/dynamic-theme/9nblggh1zbkw

Thanks Maison

**Comment by Gabboxl** [comment]
> @Gabboxl  I just saw an app whose name appears differently in the Microsoft Store for each language
> 
> Tema Dinâmico
> https://www.microsoft.com/pt-br/store/p/dynamic-theme/9nblggh1zbkw
> 
> Dynamic Theme
> https://www.microsoft.com/en-us/store/p/dynamic-theme/9nblggh1zbkw
> 
> Thanks Maison

Hi, yeah. As I said before, the listing name can be translated, but unfortunately this can't be done via Crowdin or via a shared translation file.
