### ISSUE TITLE
Wallpaper randomly fading in/out in some cases

### ISSUE THREAD

**Issue by itsWindows11** [Gabboxl/FluentWeather#3]

**Comment by Gabboxl** [comment]
Hi! Could you make a video or specify when the wallpaper shouldn't fade in/out? Currently, the wallpaper should fade when reloading data, changing measure units, and changing the place to signal the action.

**Comment by Gabboxl** [comment]
Feel free to reopen this issue if you find cases where the wallpaper shouldn't fade out, thanks!
