### ISSUE TITLE
Features & improvements

### ISSUE THREAD

**Issue by realgooseman** [Gabboxl/FluentWeather#30]
Hi @Gabboxl and contributors,

Thanks for FluentWeather, this was very needed. I opened this issue to share some improvements/ideas, let me know what you think.

### **Visibility**

The app was quite hard to find, I added it to [AlternativeTo](https://alternativeto.net/software/fluentweather/about/) and hopefully it will get more visibility.

### **Improvements**

- [ ] #48
- [ ] #49
> Example : Hide pressure and visibility tiles + hide weather insights (all tiles) + only show 4 next hourly forecasts

- [ ] Make resized app window more responsive and make tiles take full width on smaller windows.
- [ ] Add option to hide scrollbar(s)
- [ ] Replace location and last updated text with a location button. That button shows a dropdown menu of your location and last updated info + could also get a feature where we can add more than one location and switch between them in that menu.
- [ ] Move new location button + settings button + refresh button next to each other. Preferably somewhere where it doesn't overlap on other weather tiles (next to "search a place" bar for example)

### **Ideas :**

For the inspiration, you can look at the open-source Android app called [Breezy Weather](https://github.com/breezy-weather/breezy-weather) for example. The app got great responsiveness and the UI is clean. Even on desktop with WSA.

**Comment by Gabboxl** [comment]
Hi, thank you! Those are very valid ideas.

Multiple location support is coming but with a NavigationView-like design. 

Will implement your suggestions during the next few weeks. :)

**Comment by realgooseman** [comment]
Great to hear, thanks !

**Comment by realgooseman** [comment]
Forget to mention, a generalized 24H format would be nice to have as well. 
For now sunrise, sunset, moonrise, moonset tiles only show in 12H format.

> For some strange reason, the 24H format is already applied for Hourly forecasts, but not for Sun & Moon categories.

**Comment by Gabboxl** [comment]
> Forget to mention, a generalized 24H format would be nice to have as well. For now sunrise, sunset, moonrise, moonset tiles only show in 12H format.
> 
> > For some strange reason, the 24H format is already applied for Hourly forecasts, but not for Sun & Moon categories.

You're right, will add an option to choose the hours format.

**Comment by Gabboxl** [comment]
Hi, i am implementing some new features and i have some questions:

> Make resized app window more responsive and make tiles take full width on smaller windows.

What tiles are you referring to? And can you clarify what do you mean with "take full width"?

> Add option to hide scrollbar(s)

What scrollbars? Scrollbars must be visible, otherwise the user cannot know if the page is scrollable or not.

Thanks : )

**Comment by realgooseman** [comment]
Hi @Gabboxl,

This is how I currently use FluentWeather, small window on the desktop to have a quick glance at the temperature.

![Capture d'écran 2023-11-25 193515](https://github.com/Gabboxl/FluentWeather/assets/64812183/838788d2-af3f-4a6d-af43-88d2321c2000)

The app should be fully usable in full screen for people who need all the details, but also be resizable to a "mini-mode" as above.

By "hide scrollbar" I actually meant to remove the **horizontal scrolling on compact windows** (for hourly and daily forecasts) and by that you would need to limit the forecasts boxes amount to the **full width** of the window.

Also what could help with making the app look cleaner on smaller windows is moving the settings button elsewhere because it's in the way (see picture above) and make the dashboard configurable so the user can choose the details he/she wants to see. And the rest is hidden.

**Comment by Gabboxl** [comment]
> The app should be fully usable in full screen for people who need all the details, but also be resizable to a "mini-mode" as above.
> 
> By "hide scrollbar" I actually meant to remove the **horizontal scrolling on compact windows** (for hourly and daily forecasts) and by that you would need to limit the forecasts boxes amount to the **full width** of the window.
> 
> Also what could help with making the app look cleaner on smaller windows is moving the settings button elsewhere because it's in the way (see picture above) and make the dashboard configurable so the user can choose the details he/she wants to see. And the rest is hidden.

Oh alright, so you're asking for a mini-mode. thanks for the clarification : )

I will see if I can create a similar interface mode, just like the Windows Calculator/Movies apps.

**Comment by Gabboxl** [comment]
Hi, an option to change the time format has been implemented in FluentWeather v1.4.0.
The other features you asked are being tracked on #48, #49, #52 and #26. I'm closing this issue.
