### ISSUE TITLE
Hour format + detailed hourly forecast data

### ISSUE THREAD

**Issue by boydmjdk** [Gabboxl/FluentWeather#44]
I know some people (military?) like the 24 hour format, but for me, I have to do the mental math exercise (be nice) to arrive at the 12 hour format. AM/PM would be much easier or just make it optional on the app.
As an outdoor sportsman, I would like to see hourly precipitation percentage forecast

**Comment by Gabboxl** [comment]
Hi, an hour format change option is in the works. The precipitation percentage is already visible per hour, it's at the bottom of each hour weather card.

**Comment by boydmjdk** [comment]
Thanks for the rapid response, Gabriele!  I really like the app and just recently dumped MS Weather because they got too complicated and on top of that they started putting add up that I can't opt out off.  I think I will set up a recurring monthly contribution to FluentWeather for $5/month and hopefully we can keep it ad free.
Thanks again,
Michael Boyd

**Comment by Gabboxl** [comment]
Thank you, happy to know the app's serving its purpose!

**Comment by boydmjdk** [comment]
Hi Gabriel
Just a follow up.  I was wondering if hourly wind speed forecst could be included in the FW app?
Thanks
Michael Boyd

**Comment by Gabboxl** [comment]
> I was wondering if hourly wind speed forecst could be included in the FW app?

Will add more detailed hourly data very soon!

**Comment by Gabboxl** [comment]
Hour format setting + detailed hourly forecast data have been implemented in FluentWeather v1.4.0, check it out!

**Comment by boydmjdk** [comment]
Thanks Gabriele

**Comment by boydmjdk** [comment]
Hi Gabriel
Could you send me a link so that I can donate to Fluent Weather?  I really like the app.
Thanks
Michael Boyd

**Comment by Gabboxl** [comment]
> Hi Gabriel Could you send me a link so that I can donate to Fluent Weather? I really like the app.

Hi, thanks! if you really want to donate me something you can do it there: https://www.paypal.com/paypalme/gabboxl
thanks again!
