### ISSUE TITLE
Add customization of element rounding

### ISSUE THREAD

**Issue by ReginaLain** [Gabboxl/FluentWeather#58]
Good afternoon. I like your application very much, but there is an element that does not match the design of my windows. The weather elements in your app have an unpleasant rounding, which is trending now, but it doesn't match Windows 10 at all. Could you please add a customization to fix this? Ideally, of course, you could also add a classic acryl.....

**Comment by Gabboxl** [comment]
Hi, well this is the design direction of Windows 11, which is the latest iteration of the Fluent design language. In a few years Windows 10 won't be supported anymore, and I don't think sharp corners will return anytime soon in future Windows releases.

Unfortunately I don't really have much time to develop minor features for this app, so I won't implement a new way to change the overall design of the app to align it with Windows 10's design language. I'm sorry :(

Regarding acrylic, which acrylic are you referring to? The acrylic effects that are implemented currently are the Windows default ones.

**Comment by Gabboxl** [comment]
Hi, it's been almost a month since I replied but haven't gotten an answer, I'm closing the issue... if you have any requests please open it!
