### ISSUE TITLE
Hours are not translated

### ISSUE THREAD

**Issue by maisondasilva** [Gabboxl/FluentWeather#62]
Version 1.4.0

![image](https://github.com/Gabboxl/FluentWeather/assets/11423362/5961216e-e4af-4d5a-8ad0-05c92b50a0d3)

**Comment by Gabboxl** [comment]
You can translate on the FluentWeather's Crowdin project!

**Comment by maisondasilva** [comment]
@Gabboxl There is no such thing in the translation,

**Comment by Gabboxl** [comment]
> @Gabboxl There is no such thing in the translation pt-BR.

oh okay, so those strings are not translatable... will add them shortly

**Comment by maisondasilva** [comment]
Thank you so, if it is available I will do the translation, can we leave this request open?

**Comment by maisondasilva** [comment]
@Gabboxl Translation completed on Crowdin, Thank you for the great program and the quickness in fixing the bugs, merry Christmas to you and a happy new year!

**Comment by Gabboxl** [comment]
> @Gabboxl Translation completed on Crowdin, Thank you for the great program and the quickness in fixing the bugs, merry Christmas to you and a happy new year!

Merry Christmas to you too!
