### ISSUE TITLE
The weather location searched is not translated

### ISSUE THREAD

**Issue by Gaoyifei1011** [Gabboxl/FluentWeather#67]
The weather location searched is not translated

![image](https://github.com/Gabboxl/FluentWeather/assets/49179966/984f62c3-c4ce-4e4c-b526-1bab0c1be0a3)

As you can see, the searched weather location is not translated, is this a problem with the weather data source, or is it some other bug? The location shown on the picture is Hunyuan County, Datong, Shanxi, People's Republic of China, which translates into Chinese Simplified Chinese as  浑源县，大同市，山西省，中华人民共和国 (Simplified Chinese in Chinese mainland)

如图所示，搜索的天气位置并没有得到翻译，这是天气数据源的问题吗，还是其他的bug？图片上所示的位置是Hunyuan County, Datong, Shanxi, People's Republic of China，翻译成简体中文是浑源县，大同市，山西省，中华人民共和国（中国大陆地区使用简体中文）

**Comment by Gabboxl** [comment]
Hi, yes, that data comes from the weather data source which I can't control/translate, unfortunately.
