### ISSUE TITLE
New lockscreen weather widget

### ISSUE THREAD

**Issue by Radical4ever** [Gabboxl/FluentWeather#71]
hi, first awesome app, better than that crappy webapp of msn thank you for developing this, second, so windows developed a new lockscreen widget for displaying the weather:
![image](https://github.com/Gabboxl/FluentWeather/assets/83252104/ff417d61-f286-40a9-a71f-d3fbdba8d27a)
is it possible to make this for fluentweather?

**Comment by Gabboxl** [comment]
Hi, thanks!
I didn't know a widget like this existed for the lock screen, have you got any sources for that? Is this used by MSN's weather app only?

**Comment by Radical4ever** [comment]
> Hi, thanks! I didn't know a widget like this existed for the lock screen, have you got any sources for that? Is this used by MSN's weather app only?

Hi, so this is only used by the msn's weather app, fluent weather's lockscreen widget uses the old one, i managed to enable this with vivetool on recent insider versions using this link, if that kinda helps, i could not find any code related stuff about it. [Link](https://pureinfotech.com/show-weather-lock-screen-windows-11/)

**Comment by Gabboxl** [comment]
> > Hi, thanks! I didn't know a widget like this existed for the lock screen, have you got any sources for that? Is this used by MSN's weather app only?
> 
> Hi, so this is only used by the msn's weather app, fluent weather's lockscreen widget uses the old one, i managed to enable this with vivetool on recent insider versions using this link, if that kinda helps, i could not find any code related stuff about it. [Link](https://pureinfotech.com/show-weather-lock-screen-windows-11/)

Oh, so that's something undocumented and probably completely unsupported. I don't think there is any public code that will make the app create this type of widget. This is something still in development and we don't really know if it will see the light on future Windows releases.

**Comment by Radical4ever** [comment]
> > > Hi, thanks! I didn't know a widget like this existed for the lock screen, have you got any sources for that? Is this used by MSN's weather app only?
> > 
> > 
> > Hi, so this is only used by the msn's weather app, fluent weather's lockscreen widget uses the old one, i managed to enable this with vivetool on recent insider versions using this link, if that kinda helps, i could not find any code related stuff about it. [Link](https://pureinfotech.com/show-weather-lock-screen-windows-11/)
> 
> Oh, so that's something undocumented and probably completely unsupported. I don't think there is any public code that will make the app create this type of widget. This is something still in development and we don't really know if it will see the light on future Windows releases.

Ok, thanks
