### ISSUE TITLE
Settings causes app flicker for first-time

### ISSUE THREAD

**Issue by hl2guide** [Gabboxl/FluentWeather#73]
The first time you click the settings cog icon it causes the app window to flicker.

Only happens once per app launch.

Tested in version 1.4.2 on WIndows 11.

**Comment by Gabboxl** [comment]
Hi, with "flicker" are you referring to the background effect when reloading weather data?

**Comment by hl2guide** [comment]
> Hi, with "flicker" are you referring to the same background effect when reloading weather data?

No, it's more like the back window shows (no background).

e.g.

![Animation](https://github.com/Gabboxl/FluentWeather/assets/17044982/927b549a-39b9-48f1-8cc3-cd5cceb59322)

**Comment by Gabboxl** [comment]
> > Hi, with "flicker" are you referring to the same background effect when reloading weather data?
> 
> No, it's more like the back window shows (no background).
> 
> e.g.
> 
> ![Animation](https://github.com/Gabboxl/FluentWeather/assets/17044982/927b549a-39b9-48f1-8cc3-cd5cceb59322)
> 

This is probably due to the loading of the image for the refresh. If you try to refresh the data instead of opening the settings at startup do you notice the same problem?

**Comment by hl2guide** [comment]
> > > Hi, with "flicker" are you referring to the same background effect when reloading weather data?
> > 
> > 
> > No, it's more like the back window shows (no background).
> > e.g.
> > ![Animation](https://private-user-images.githubusercontent.com/17044982/309587139-927b549a-39b9-48f1-8cc3-cd5cceb59322.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MzY1MDYsIm5iZiI6MTcwOTUzNjIwNiwicGF0aCI6Ii8xNzA0NDk4Mi8zMDk1ODcxMzktOTI3YjU0OWEtMzliOS00OGYxLThjYzMtY2Q1Y2NlYjU5MzIyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA3MTAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlMDc4ZDk2YjM0YWNmNzIwOWFlMTcxNWM1N2NkMjk0MjViNjZhNmQyOTcyMTkxYjcxZDlhMjgzNGVlYTY5YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9BP8KpCG18MIQha3jHtEm3GS7BrmZnNUiYYpFLnHbWo)
> >       
> >         [
> >           
> >         
> >             ![Animation](https://private-user-images.githubusercontent.com/17044982/309587139-927b549a-39b9-48f1-8cc3-cd5cceb59322.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MzY1MDYsIm5iZiI6MTcwOTUzNjIwNiwicGF0aCI6Ii8xNzA0NDk4Mi8zMDk1ODcxMzktOTI3YjU0OWEtMzliOS00OGYxLThjYzMtY2Q1Y2NlYjU5MzIyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA3MTAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlMDc4ZDk2YjM0YWNmNzIwOWFlMTcxNWM1N2NkMjk0MjViNjZhNmQyOTcyMTkxYjcxZDlhMjgzNGVlYTY5YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9BP8KpCG18MIQha3jHtEm3GS7BrmZnNUiYYpFLnHbWo)
> >           ](https://private-user-images.githubusercontent.com/17044982/309587139-927b549a-39b9-48f1-8cc3-cd5cceb59322.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MzY1MDYsIm5iZiI6MTcwOTUzNjIwNiwicGF0aCI6Ii8xNzA0NDk4Mi8zMDk1ODcxMzktOTI3YjU0OWEtMzliOS00OGYxLThjYzMtY2Q1Y2NlYjU5MzIyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA3MTAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlMDc4ZDk2YjM0YWNmNzIwOWFlMTcxNWM1N2NkMjk0MjViNjZhNmQyOTcyMTkxYjcxZDlhMjgzNGVlYTY5YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9BP8KpCG18MIQha3jHtEm3GS7BrmZnNUiYYpFLnHbWo)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/17044982/309587139-927b549a-39b9-48f1-8cc3-cd5cceb59322.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MzY1MDYsIm5iZiI6MTcwOTUzNjIwNiwicGF0aCI6Ii8xNzA0NDk4Mi8zMDk1ODcxMzktOTI3YjU0OWEtMzliOS00OGYxLThjYzMtY2Q1Y2NlYjU5MzIyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA3MTAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlMDc4ZDk2YjM0YWNmNzIwOWFlMTcxNWM1N2NkMjk0MjViNjZhNmQyOTcyMTkxYjcxZDlhMjgzNGVlYTY5YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9BP8KpCG18MIQha3jHtEm3GS7BrmZnNUiYYpFLnHbWo)
> 
> This is probably due to the loading of the image for the refresh. If you try to refresh the data instead of opening the settings at startup do you notice the same problem?

No problem for the refresh button.
