### ISSUE TITLE
Changing unit type results in some weird results where numbers change, but units don't.

### ISSUE THREAD

**Issue by Benjin** [Gabboxl/FluentWeather#75]
![image](https://github.com/Gabboxl/FluentWeather/assets/1609827/98ff1811-1f92-4d83-bc43-7bf7ca4a84ed)

* Wind: units are the same between Hybrid and Imperial, but speed and direction changed.
* Pressure: Number is all the same, despite the units being different
* Humidity: Hybrid is different from both Imperial and Metric, despite the units being the same.
* Visibility: units are the same between Metric and Hybrid, but the distance changed.

Appears that there's some incorrect conversion going on under the covers.  Or, if the API is returning these values based on a "units" parameter, it's not a very good API...

**Comment by Gabboxl** [comment]
Hi, this is a known problem from the API... the problem is a delay in updating the data for each unit of measure. The delay usually is <30 mins, I know this is not ideal but we can still consider the information up-to-date, though.

**Comment by Benjin** [comment]
what if you just picked one API flavor to call and did the unit conversions locally?
