### ISSUE TITLE
Obtained weather information is localized according to the language of the system.

### ISSUE THREAD

**Issue by WhatDamon** [Gabboxl/FluentWeather#81]
eg. Beijing -> 北京 | Tokyo -> 東京
There is also a lot of information that also can be localized, such as the UV index “Very High”.

**Comment by Gabboxl** [comment]
Hi, translated city names are the expected behavior. some may be not translated, but unfortunately I can't control them as they are coming from the API.

If you would like to translate FluentWeather-specific words (as Very High) you can do this in Crowdin
