### ISSUE TITLE
Some strings are not translated nor translatable via CrowdIn

### ISSUE THREAD

**Issue by Zhanyuanium** [Gabboxl/FluentWeather#86]
As below: 
![屏幕截图 2024-09-20 155813](https://github.com/user-attachments/assets/e552bd00-e909-4569-9953-53f5a4a226f9)
![屏幕截图 2024-09-20 160017](https://github.com/user-attachments/assets/b62d8521-7fa8-4ed6-bbdc-f19cc146447a)

Please add these items into the resw files, and I am willing to help to translate them into Chinese Simplified (zh_cn)!

**Comment by Gabboxl** [comment]
This is not possible unfortunately, those strings are coming directly from the weather API, which I can't control.
