### ISSUE TITLE
Weather Widget pileing up together with music player widget

### ISSUE THREAD

**Issue by dynosauraus0803** [Gabboxl/FluentWeather#93]
It seems like the new music player widget in Win11 23H2 update has caused to pile up together with the weather widget. I don't know if it's possible to fix it but if it's possible please fix it thanks! (Here's an example pic)
![IMG_20241217_160949_edit_785446232024419](https://github.com/user-attachments/assets/b641aa8d-2f3c-406c-b730-275cdd33b631)

**Comment by Gabboxl** [comment]
This is a Windows bug. I cannot do anything to fix this.
